package com.example.api.services.impl;

import com.example.api.domain.entity.AuthorEntity;
import com.example.api.repositories.AuthorRepository;
import com.example.api.services.AuthorService;
import org.springframework.stereotype.Service;

@Service
public class AuthorServiceImpl implements AuthorService {
    private final AuthorRepository authorRepository;

    public AuthorServiceImpl(AuthorRepository authorRepository) {
        this.authorRepository = authorRepository;
    }

    /**
     * Saves new author entity. ID auto-generated by SEQUENCE.
     * Implied transactional through JPA.
     */
    @Override
    public AuthorEntity createAuthor(AuthorEntity authorEntity) {
        return authorRepository.save(authorEntity);
    }
}
